### PR TITLE
Partition address table to speed up partial searches

### LINKED ISSUE #124: Partial requests fail due to timeouts (32 seconds)
Partial requests seem to be causing a rather large database load that lead to 502 errors due to connection timeouts.

After a discussion with Alistair we decided that partitioning the table based on the first characters of the postcode itself. This is a PostgreSQL specific feature.

This functionality can be enabled/achieved through Django transparently using the [Architect library](http://architect.readthedocs.org/index.html)

### PR DESCRIPTION
**Pull request by aldavidson**
fixes #124 - partial postcode searches very slow - and also fixes identification of the appropriate country on partial searches, by partitioning the address table based on first character of the postcode_index, and calculating partial centroids entirely in the database

### CODE REVIEW

File: scripts/addressbase_import.sh [hunk 1]
```diff
@@ -126,6 +126,18 @@ function convert_data_sql {
...
+    for first_char in {a..z} {0..9}
+    do
+      echo "SELECT 'deleting from ${LIVE_TABLE_NAME}_${first_char}' AS status;"
+      echo "TRUNCATE TABLE ${LIVE_TABLE_NAME}_${first_char};"
+      echo "SELECT 'inserting into ${LIVE_TABLE_NAME}_${first_char}' AS status;"
+      echo "INSERT INTO ${LIVE_TABLE_NAME}_${first_char}
+            SELECT * FROM $OFFLINE_TABLE_NAME
+            WHERE postcode_index LIKE '$first_char%';"
+    done
+
```
Comment (niallcreech) [inline scripts/addressbase_import.sh]: @aldavidson the closing bracket thing here
